const SimpleNFTSellerContract = {
  MAINNET_ADDRESS: "0x58d782a6222D93430FCD3DbfD8b639911A0AB4Ec",
  TESTNET_ADDRESS: "",
  ABI: [
    {
      inputs: [
        {
          internalType: "address payable",
          name: "_feeRecipient",
          type: "address",
        },
        { internalType: "uint256", name: "_platformFee", type: "uint256" },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "owner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "nft",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "tokenId",
          type: "uint256",
        },
      ],
      name: "ItemCanceled",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "owner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "nft",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "tokenId",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "quantity",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "pricePerItem",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "startingTime",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "bool",
          name: "isPrivate",
          type: "bool",
        },
        {
          indexed: false,
          internalType: "address",
          name: "allowedAddress",
          type: "address",
        },
      ],
      name: "ItemListed",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "seller",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "buyer",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "nft",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "tokenId",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "price",
          type: "uint256",
        },
      ],
      name: "ItemSold",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "owner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "nft",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "tokenId",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "newPrice",
          type: "uint256",
        },
      ],
      name: "ItemUpdated",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "creator",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "nft",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "tokenId",
          type: "uint256",
        },
      ],
      name: "OfferCanceled",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "creator",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "nft",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "tokenId",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "address",
          name: "payToken",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "quantity",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "pricePerItem",
          type: "uint256",
        },
        {
          indexed: false,
          internalType: "uint256",
          name: "deadline",
          type: "uint256",
        },
      ],
      name: "OfferCreated",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "previousOwner",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "newOwner",
          type: "address",
        },
      ],
      name: "OwnershipTransferred",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "uint256",
          name: "platformFee",
          type: "uint256",
        },
      ],
      name: "UpdatePlatformFee",
      type: "event",
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: "address payable",
          name: "platformFeeRecipient",
          type: "address",
        },
      ],
      name: "UpdatePlatformFeeRecipient",
      type: "event",
    },
    {
      inputs: [
        { internalType: "address", name: "_nftAddress", type: "address" },
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "address", name: "_creator", type: "address" },
      ],
      name: "acceptOffer",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_nftAddress", type: "address" },
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
      ],
      name: "buyItem",
      outputs: [],
      stateMutability: "payable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_nftAddress", type: "address" },
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
      ],
      name: "cancelListing",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_nftAddress", type: "address" },
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
      ],
      name: "cancelOffer",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_nftAddress", type: "address" },
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "contract IERC20", name: "_payToken", type: "address" },
        { internalType: "uint256", name: "_quantity", type: "uint256" },
        { internalType: "uint256", name: "_pricePerItem", type: "uint256" },
        { internalType: "uint256", name: "_deadline", type: "uint256" },
      ],
      name: "createOffer",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "feeReceipient",
      outputs: [{ internalType: "address payable", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_nftAddress", type: "address" },
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "uint256", name: "_quantity", type: "uint256" },
        { internalType: "uint256", name: "_pricePerItem", type: "uint256" },
        { internalType: "uint256", name: "_startingTime", type: "uint256" },
        { internalType: "address", name: "_allowedAddress", type: "address" },
      ],
      name: "listItem",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "uint256", name: "", type: "uint256" },
      ],
      name: "listings",
      outputs: [
        { internalType: "address payable", name: "owner", type: "address" },
        { internalType: "uint256", name: "quantity", type: "uint256" },
        { internalType: "uint256", name: "pricePerItem", type: "uint256" },
        { internalType: "uint256", name: "startingTime", type: "uint256" },
        { internalType: "address", name: "allowedAddress", type: "address" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "", type: "address" },
        { internalType: "uint256", name: "", type: "uint256" },
        { internalType: "address", name: "", type: "address" },
      ],
      name: "offers",
      outputs: [
        { internalType: "contract IERC20", name: "payToken", type: "address" },
        { internalType: "uint256", name: "quantity", type: "uint256" },
        { internalType: "uint256", name: "pricePerItem", type: "uint256" },
        { internalType: "uint256", name: "deadline", type: "uint256" },
      ],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "owner",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "platformFee",
      outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "renounceOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
      name: "transferOwnership",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "_nftAddress", type: "address" },
        { internalType: "uint256", name: "_tokenId", type: "uint256" },
        { internalType: "uint256", name: "_newPrice", type: "uint256" },
      ],
      name: "updateListing",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        { internalType: "uint256", name: "_platformFee", type: "uint256" },
      ],
      name: "updatePlatformFee",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [
        {
          internalType: "address payable",
          name: "_platformFeeRecipient",
          type: "address",
        },
      ],
      name: "updatePlatformFeeRecipient",
      outputs: [],
      stateMutability: "nonpayable",
      type: "function",
    },
  ],
};

module.exports = SimpleNFTSellerContract;
